CREATE TABLE category (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(255),
    PRIMARY KEY (id)
);

INSERT INTO category (name) VALUES 
('Tecnología'),
('Psicología'),
('Ciencia Ficción'),
('Poesía'),
('Drama'),
('Negocios'),
('Educación'),
('Salud y Bienestar'),
('Arte'),
('Religión'),
('Cocina'),
('Viajes'),
('Humor'),
('Política'),
('Ecología'),
('Filosofía'),
('Literatura Clásica'),
('Economía'),
('Deportes'),
('Infantil'),
('Juvenil'),
('Suspenso'),
('Autoayuda Profesional'),
('Relaciones Personales'),
('Historia'),
('Biografías'),
('Romance'),
('Fantasía'),
('Misterio'),
('Terror'),
('Aventura'),
('Crimen'),
('Autoayuda');